# The current version is undefined as this is still a draft
version = "0.0.0"

github = "lrpm-proto/spec"

uri_definitions = [
  { uri = ".err.auth", desc = "Bad auth error occurred" },
  { uri = ".err.proto", desc = "Protocol error occurred" },
  { uri = ".err.cancelled", desc = "Request was cancelled" },
  { uri = ".bye.normal", desc = "Normal closing event" }
]

###############################################################################

[[session.stages]]
name = "INIT"
desc = "Session is initialising"

[[session.stages]]
name = "AUTH"
desc = "Session is authenticating"

[[session.stages]]
name = "OKAY"
desc = "Session is established"

###############################################################################

[[basic_types]]
name = "u8"
desc = "An unsigned 8-bit integer"

[[basic_types]]
name = "u64"
desc = "An unsigned 64-bit integer"

[[basic_types]]
name = "str"
desc = "An ASCII encoded string"

[[basic_types]]
name = "map"
desc = "A `str` key to `val` structure"

[[basic_types]]
name = "val"
desc = "A generic value tagged with its type"

###############################################################################

[[special_types]]
name = "id"
extends = ["u8"]
desc = "Represents a single request unique within a session"

[[special_types]]
name = "uri"
extends = ["str"]
desc = "Represents a resource unique across all sessions"
constraints = [
  "`MUST NOT` start with a `.` (reserved for LRPMP use)",
  "`SHOULD` be limited to the characters `_`, `.`, `*`, `a-z` and `0-9`",
  "`SHOULD NOT` have `*` or `.` in a sequence of more than one (eg `**`, `..`)",
  "`_`, `a-z` and `0-9` `SHOULD` be used for resource identification",
  "The character `.` `SHOULD` represent a namespace separator",
  "The character `*` `SHOULD` represent a wildcard (only valid for topics)"
]

[[special_types]]
name = "kind"
extends = ["u8", "str"]
desc = "Represents a message kind (eg, `CALL`, `40`)"
constraints = [
  "`str` form `MUST` be limited to the characters `A-Z` and `_`"
]

[[special_types]]
name = "meta"
extends = ["map"]
desc = "An arbitrary map of optional additional information"

[[special_types]]
name = "body"
extends = ["val"]
desc = "An application specific value"

###############################################################################

[[message.types]]
name = "SESSION"
desc = "Messages used within a session, but not tied to a request"

[[message.types]]
name = "REQUEST"
desc = "Messages with a request ID that require a response"

[[message.types]]
name = "RESPONSE"
desc = "Messages responding to a request"

###############################################################################

[[messages]]
code = 1
name = "GOODBYE"
type = "SESSION"
stages = ["INIT", "AUTH", "OKAY"]
desc = """
"""

[[messages.fields]]
name = "reason"
type = "uri"
desc = "A URI uniquely describing the close reason"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 2
name = "HELLO"
type = "SESSION"
stages = ["INIT"]
desc = """
"""

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the message"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 3
name = "PROVE"
type = "SESSION"
stages = ["AUTH"]
desc = """
"""

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the message"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 4
name = "PROOF"
type = "SESSION"
stages = ["AUTH"]
desc = """
"""

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the message"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 20
name = "ERROR"
type = "RESPONSE"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_kind"
type = "kind"
desc = "The request kind that triggered the error"

[[messages.fields]]
name = "request_id"
type = "id"
desc = "The request ID that triggered the error"

[[messages.fields]]
name = "error"
type = "uri"
desc = "A URI uniquely describing the error"

[[messages.fields]]
name = "body"
type = "body"
desc = "Body of the error message"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 21
name = "CANCEL"
type = "REQUEST"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "The ID of the request we want to cancel"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 40
name = "CALL"
type = "REQUEST"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "An ID uniquely describing the call request"

[[messages.fields]]
name = "procedure"
type = "uri"
desc = "A URI uniquely describing the procedure"

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the message"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 41
name = "RESULT"
type = "RESPONSE"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "The ID of the call we are responding to"

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the message"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 60
name = "EVENT"
type = "SESSION"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "publication_id"
type = "id"
desc = "The publication ID"

[[messages.fields]]
name = "subscription_id"
type = "id"
desc = "The subscription ID"

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the event"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 61
name = "PUBLISH"
type = "REQUEST"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "An ID uniquely describing the publication request"

[[messages.fields]]
name = "topic"
type = "uri"
desc = "A URI describing the topic we are publishing to"

[[messages.fields]]
name = "body"
type = "body"
desc = "The body of the event being published"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 62
name = "PUBLISHED"
type = "RESPONSE"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "The ID of the publication request"

[[messages.fields]]
name = "publication_id"
type = "id"
desc = "An ID uniquely describing the publication"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 63
name = "SUBSCRIBE"
type = "REQUEST"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "An ID uniquely describing the subscription request"

[[messages.fields]]
name = "topic"
type = "uri"
desc = "A URI describing the topic we are subscribing to"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 64
name = "SUBSCRIBED"
type = "RESPONSE"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "The ID of the subscription request"

[[messages.fields]]
name = "subscription_id"
type = "id"
desc = "An ID uniquely describing the subscription"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 65
name = "UNSUBSCRIBE"
type = "REQUEST"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "An ID uniquely describing the unsubscribe request"

[[messages.fields]]
name = "subscription_id"
type = "id"
desc = "The subscription ID we are unsubscribing from"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"

###############################################################################

[[messages]]
code = 66
name = "UNSUBSCRIBED"
type = "RESPONSE"
stages = ["OKAY"]
desc = """
"""

[[messages.fields]]
name = "request_id"
type = "id"
desc = "The ID of the unsubscribe request"

[[messages.fields]]
name = "meta"
type = "meta"
desc = "Optional meta information on this message"
